config/routes.rb
Rails.application.routes.draw do
  resources :room_messages
  devise_for :users
  root to: 'pages#home'
  post "/set_user_team", to: "teams#set_user_team", as: :set_user_team
  post "/set_user_game", to: "pages#set_user_game", as: :set_user_game
  resources :games, only: [ :index, :show ] do
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :teams, only: [:show, :index, :new, :create] do
    resources :positions
    resources :pending_applications, only: [ :index, :create ]
    resources :rooms
  end

  get 'positions', to: 'positions#all'
  post 'captain_approve', to: 'pending_applications#captain_approve'
  post 'player_approve', to: 'pending_applications#player_approve'

  post 'create_default_positions', to: 'positions#create_default_positions'
  post 'delete_all_positions', to: 'positions#delete_all_positions'

  get 'ranks', to: 'players#ranks'

  get 'create_invitation', to: 'pending_applications#create_invitation'

  resources :players, only: [ :index, :show ]
  resources :pending_applications, only: [ :destroy ]

end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :position_name
  belongs_to :user, optional: true
  belongs_to :team
  has_many :pending_applications, dependent: :destroy
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_team, only: %i[index new update create_default_positions delete_all_positions]

  def index
    @rooms = Room.where(team_id: @team.id)
    @positions = Position.where(team_id: @team).order(id: :desc)
    @applied = []

    user_applications = PendingApplication.where(user_id: current_user)

    user_applications.each do |user|
      @applied << user.position_id
    end
  end

  def all
    @positions = Position.all
  end

  def update
    @position = Position.find(params[:id])
    @position.user = nil
    @position.save
    redirect_to request.referrer
  end

  def new
    @position_names = PositionName.where(game_id: @team.game)
    @position = Position.new
  end

  def create(position_name = "")
    # Team.find can't be in the before_action because we are using in the
    # create default positions method
    @team = Team.find(params[:team_id]) # dont remove

    @position = Position.new
    @position.team = @team
    if position_name == ""
      @position_name = PositionName.find(params[:position][:position_name])
    else
      @position_name = PositionName.find_by(name: position_name)
    end
    @position.position_name = @position_name
    @position.save

    redirect_to team_positions_path(@team.id) if position_name == ""
  end

  def destroy
    @position = Position.find(params[:id])
    @position.destroy

    redirect_to team_positions_path(params[:team_id])
  end

  def clear_position
    redirect_to team_positions_path(@position.team_id)
  end

  def create_default_positions
    dota2 = %w[Carry Jungler Offlaner Support Support]
    csgo = %w[Leader Fragger AWPer Lurker Playmaker]
    @team.game_id == 1 ? game = dota2 : game = csgo
    game.each do |position_name|
      create(position_name)
    end

    redirect_to request.referrer
  end

  def delete_all_positions
    @team.positions.each(&:destroy)
    redirect_to request.referrer
  end

  private

  def set_team
    @team = Team.find(params[:team_id])
  end
end

app/views/positions/index.html.erb
  <div class="container-top">

    <div class="top-left">
      <% if @team.captain?(current_user) %>
        <%= link_to new_team_position_path(@team.id) do %>
          <div class="team-positions-index-button">CREATE A POSITION </div>
        <% end %>
        <%= link_to create_default_positions_path(team_id: @team.id), method: :post do %>
          <div class="team-positions-index-button">DEFAULT POSITIONS</div>
        <% end %>
        <%= link_to delete_all_positions_path(team_id: @team.id), method: :post do %>
          <div class="team-positions-index-button">DELETE ALL POSITIONS</div>
        <% end %>
        <%= link_to team_pending_applications_path(@team) do %>
          <div class="team-positions-index-button">REVIEW APPLICATIONS</div>
        <% end %>
      <% else %>
      <% end %>
    </div>
    <div class="top-center">
      <%= cl_image_tag @team.photo.key, height: 200, width: 200, crop: :fill, class: "team-logo", alt: "team logo" %>
    </div>

    <div class="top-right">
      <%= image_tag "dota-rank11.png", height: 150, width: 150 %>
    </div>
  </div>

  <h2 class="team-name"><%= @team.name.upcase %></h2>
  <div class='cards-player'>
    <% @positions.each do|position| %>
      <div class="card-wrapper-player">
        <% if position.user.nil? %>
          <div class="position-empty-card">
            <h2>EMPTY SLOT</h2>
            <p><%= position.position_name.name %></p>
            <% if @applied.include?(position.id) %>
              <div class="player-button-black ml-5">APPLIED</div>
            <% else %>
              <%= link_to team_pending_applications_path(@team, position_id:position.id), method: :post do %>
                <div class="player-button-orange ml-5">APPLY</div>
              <% end %>
            <% end %>
          </div>
        <% else %>
          <div class="card-wrapper-player-flex">
            <%= link_to root_path do %>
              <div class="avatar-square-player">
                <% if position.user.photo.attached? %>
                  <%= cl_image_tag position.user.photo.key, height: 150, width: 150, crop: :thumb, gravity: :face %>
                <% else %>
                  <%= image_tag "avatar_logo.jpg", height: 150, width: 150 %>
                <% end %>
              </div>
            <% end %>
            <div class="card-position">
              <h3><%= position.user.nickname %></h3>
              <br>
              <p>
                <% if current_user.show_game == "2" && position.user.position_name.name == "Jungler" %>
                  Playmaker
                <% else %>
                  <%= position.user.position_name.name %></p>
                <% end %>
              <div class="card-buttons">
                <% if @team.captain?(current_user) %>
                  <%= link_to team_position_path(@team, id:position.id), method: :put do %>
                    <div class="player-button-orange">REMOVE</div>
                  <% end %>
                  <%= link_to team_position_path(@team.id, position.id), method: :delete,
                  data: { confirm: "Are you sure?" } do %>
                    <div class="player-button-black">DELETE</div>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="card-rank card-position-image">
              <% if position.user.rank.game.id == 1 %>
                <%= image_tag position.user.rank.image, height: 50, width: 50, crop: :fill %>
              <% else %>
                <%= image_tag position.user.rank.image, height: 25, width: 50, crop: :fill %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<br><br>

  <div class="chat">
    <div><%= link_to "CREATE A CHAT ROOM", new_team_room_path(@team.id), class: "btn btn-dark btn-lrg" %></div>
  </div>
    <% if @rooms.present? %>
      <% @rooms.each do |room| %>
        <div class="chat-rooms-list">
        <%= link_to room.name, team_room_path(@team, room), class: "nav-link room-nav-link" %>
         <%= link_to "Delete room", team_room_path(@team.id, room.id),
                method: :delete,
                data: { confirm: "Are you sure?" } %>
                </div>
      <% end %>
  <% else %>
    <div class="chat-rooms-list">
      <p id="chat-rooms-empty-list">Create your first team chat room!</p>
    </div>
  <% end %>
  <br><br> <br><br>
</div>

app/views/positions/new.html.erb
<%= simple_form_for [@team, @position] do |f| %>
  <%= f.input :position_name, as: :select, collection: @position_names, prompt: 'Select a position name', label: false %>
  <%= f.submit "Add a position", class: "btn btn-primary" %>
<% end %>