config/routes.rb
Rails.application.routes.draw do
  resources :room_messages
  devise_for :users
  root to: 'pages#home'
  post "/set_user_team", to: "teams#set_user_team", as: :set_user_team
  post "/set_user_game", to: "pages#set_user_game", as: :set_user_game
  resources :games, only: [ :index, :show ] do
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :teams, only: [:show, :index, :new, :create] do
    resources :positions
    resources :pending_applications, only: [ :index, :create ]
    resources :rooms
  end

  get 'positions', to: 'positions#all'
  post 'captain_approve', to: 'pending_applications#captain_approve'
  post 'player_approve', to: 'pending_applications#player_approve'

  post 'create_default_positions', to: 'positions#create_default_positions'
  post 'delete_all_positions', to: 'positions#delete_all_positions'

  get 'ranks', to: 'players#ranks'

  get 'create_invitation', to: 'pending_applications#create_invitation'

  resources :players, only: [ :index, :show ]
  resources :pending_applications, only: [ :destroy ]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-find">
  <!-- left section -->
  <div class="left-logo">
    <%= link_to root_path, class: "navbar-brand" do %>
      <% if current_user.nil? || current_user.show_game == "1" %>
          <%= image_tag "find_logo_dota2_transparent.png", height: 65, width: 151, crop: :fill %>
        <% elsif current_user.show_game == "2" %>
          <%= image_tag "find_logo_csgo_transparent.png", height: 65, width: 151, crop: :fill %>
      <% end %>
    <% end %>
  </div>


  <!-- middle section -->
  <div class="text-center-navbar">
    <% if user_signed_in? %>
      <% if current_user.photo.attached? %>
        <%= cl_image_tag(current_user.photo.key, class: "avatar-new dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, width: 70, height: 70, crop: :fill, gravity: :face) %>
      <% else %>
        <%= image_tag "avatar_logo.jpg", class: "avatar-new dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% end %>

      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to "Your Profile", player_path(current_user), class: "dropdown-item" %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    <% else %>
      <div class="d-flex justify-content-center">

       <%= link_to "Login", new_user_session_path, class: "nav-link" %>

      </div>
    <% end %>
      <ul class="nav nav-tabs d-flex <%= current_user.nil? ? "dota" : current_user.show_game == "1" ? "dota" : "csgo" %> ">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link #{ 'active-tab' if controller_name == 'pages' && action_name == 'home'}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Teams", teams_path, class: "nav-link #{ 'active-tab' if controller_name == 'teams' && action_name == 'index'}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Players", players_path, class: "nav-link #{ 'active-tab' if controller_name == 'players' && action_name == 'index'}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Create a Team", new_team_path, class: "nav-link #{ 'active-tab' if controller_name == 'teams' && action_name == 'new'}" %>
        </li>
        <% if current_user %>
        <li class="nav-item">
          <%= link_to "Your Profile", player_path(current_user), class: "nav-link #{ 'active-tab' if controller_name == 'players' && action_name == 'show'}" %>
        </li>
        <% end %>
      </ul>

  </div>

  <!-- right section -->

  <div class="game-logo">
    <% if current_user.nil? || current_user.show_game == "1" %>
        <%= image_tag "dota2_logo.png", height: 75, width: 120, crop: :fill %>
      <% elsif current_user.show_game == "2" %>
        <%= image_tag "csgo_logo.png" %>
    <% end %>
  </div>

</div>