config/routes.rb
Rails.application.routes.draw do
  resources :room_messages
  devise_for :users
  root to: 'pages#home'
  post "/set_user_team", to: "teams#set_user_team", as: :set_user_team
  post "/set_user_game", to: "pages#set_user_game", as: :set_user_game
  resources :games, only: [ :index, :show ] do
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :teams, only: [:show, :index, :new, :create] do
    resources :positions
    resources :pending_applications, only: [ :index, :create ]
    resources :rooms
  end

  get 'positions', to: 'positions#all'
  post 'captain_approve', to: 'pending_applications#captain_approve'
  post 'player_approve', to: 'pending_applications#player_approve'

  post 'create_default_positions', to: 'positions#create_default_positions'
  post 'delete_all_positions', to: 'positions#delete_all_positions'

  get 'ranks', to: 'players#ranks'

  get 'create_invitation', to: 'pending_applications#create_invitation'

  resources :players, only: [ :index, :show ]
  resources :pending_applications, only: [ :destroy ]

end

app/models/pending_application.rb
class PendingApplication < ApplicationRecord
  belongs_to :user
  belongs_to :position
end

app/controllers/pending_applications_controller.rb
class PendingApplicationsController < ApplicationController
  before_action :set_application, only: %i[show destroy captain_approve player_approve]

  def index
    @team = Team.find(params[:team_id])
    @is_captain = captain?(@team)
    @pending_applications = @team.pending_applications
  end

  def captain?(team)
    team.user == current_user
  end

  def captain_approve
    team = Team.find(params[:team_id])
    @pending_application.owner_approval = true
    @pending_application.save

    fill_position
    redirect_to team_positions_path(team)
  end

  def player_approve
    team_id = @pending_application.position.team.id
    team = Team.find(team_id)
    @pending_application.user_approval = true
    @pending_application.save

    fill_position
    redirect_to team_positions_path(team)
  end

  def fill_position
    @position = Position.find(@pending_application.position.id)
    if @position.user.nil?
      if @pending_application.owner_approval && @pending_application.user_approval
        @position.user = @pending_application.user
        @position.save
        destroy
      end
    end
  end

  def show
  end

  def create
    @position = Position.find(params[:position_id])
    @pending_application = PendingApplication.new
    @pending_application.user = current_user
    @pending_application.position = @position
    if @pending_application.position.team.captain?(current_user)
      @pending_application.owner_approval = true
      @pending_application.user_approval = true
    else
      @pending_application.user_approval = true
    end

    if @pending_application.save
      fill_position
      redirect_to team_positions_path(@position.team)
    else
      redirect_to request.referrer
    end
  end

  def destroy
    @pending_application.destroy
    redirect_to request.referrer if params[:action] == "destroy"
  end

  def create_invitation
    # Currently only works if you select everything correctly
    @player = User.find(params[:player])
    @captain = current_user
    @team = @captain.teams.where(game_id: params[:game_id]).first
    @position = @team.positions.where(position_name_id: params[:position]).first
    # Bryan's code from here onwards
    @pending_application = PendingApplication.new
    @pending_application.user = @player
    @pending_application.position = @position
    @pending_application.owner_approval = true
    if @pending_application.save
      fill_position
      redirect_to team_positions_path(@position.team)
    else
      redirect_to request.referrer
    end
  end

  private

  def set_application
    @pending_application = PendingApplication.find(params[:id])
  end
end

app/views/pending_applications/create_invitation.html.erb
<h1>Invitation for <%= @player.nickname%></h1>
<%= @team.name %>
<%= @position.position_name.name %>

app/views/pending_applications/index.html.erb
<div class="d-flex align-items-center py-3">
      <div class="category">
      <div class="p-2 bg-gradient-dark mr-5">FILTER BY</div>
      <div class="p-2 bg-gradient-dark mr-5">POSITION</div>
      <div class="p-2 bg-gradient-dark mr-5">RANK</div>
      <div class="p-2 bg-gradient-dark mr-5">SEARCH</div>


      <%= form_tag players_path, method: :get, class: "form-inline" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "ENTER NICKNAME",
          autocomplete: "off"
        %>
      <% end %>
      </div>
    </div>
  <div class="cards-main-player">

    <div class="cards-player" >
      <% @pending_applications.each do|pending_application| %>
        <div class="card-wrapper-player">
          <div class="card-wrapper-player-flex">
            <%= link_to player_path(pending_application.user) do %>
              <div class="avatar-square-player">
                <% if pending_application.user.photo.attached? %>
                  <%= cl_image_tag pending_application.user.photo.key, height: 150, width: 150, crop: :thumb, gravity: :face %>
                <% else %>
                  <%= image_tag "avatar_logo.jpg", height: 150, width: 150 %>
                <% end %>
              </div>
            <% end %>
            <div class="card-position">
              <h3><%= pending_application.user.nickname %></h3>
              <p><%= pending_application.position.position_name.name %></p>
              <div class="card-buttons">
                <% if @is_captain %>
                  <% if pending_application.owner_approval == false && pending_application.user_approval %>
                    <%= link_to captain_approve_path(team_id:@team.id, id:pending_application.id), method: :post do %>
                      <div class="player-button-orange">APPROVE</div>
                    <% end %>
                    <%= link_to pending_application_path(pending_application), method: :delete do %>
                      <div class="player-button-red">REJECT</div>
                    <% end %>
                  <% elsif pending_application.owner_approval && !pending_application.user_approval %>
                    <div class="player-button-green">INVITED</div>
                    <%= link_to pending_application_path(pending_application), method: :delete do %>
                      <div class="player-button-red">DELETE</div>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="card-position-image">
              <% if pending_application.user.rank.game.id == 1 %>
                <%= image_tag pending_application.user.rank.image, height: 50, width: 50, crop: :fill %>
              <% else %>
                <%= image_tag pending_application.user.rank.image, height: 25, width: 50, crop: :fill %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>