config/routes.rb
Rails.application.routes.draw do
  resources :room_messages
  devise_for :users
  root to: 'pages#home'
  post "/set_user_team", to: "teams#set_user_team", as: :set_user_team
  post "/set_user_game", to: "pages#set_user_game", as: :set_user_game
  resources :games, only: [ :index, :show ] do
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :teams, only: [:show, :index, :new, :create] do
    resources :positions
    resources :pending_applications, only: [ :index, :create ]
    resources :rooms
  end

  get 'positions', to: 'positions#all'
  post 'captain_approve', to: 'pending_applications#captain_approve'
  post 'player_approve', to: 'pending_applications#player_approve'

  post 'create_default_positions', to: 'positions#create_default_positions'
  post 'delete_all_positions', to: 'positions#delete_all_positions'

  get 'ranks', to: 'players#ranks'

  get 'create_invitation', to: 'pending_applications#create_invitation'

  resources :players, only: [ :index, :show ]
  resources :pending_applications, only: [ :destroy ]

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def show
    @player = User.find(params[:id])
    @pending_applications = PendingApplication.where(user_id: @player.id)
  end

  def index
    # @players = User.all

    if params[:query].present?
      sql_query = "nickname ILIKE :query OR show_game ILIKE :query OR email ILIKE :query"
      @players = User.where(sql_query, query: "%#{params[:query]}%")
    else
      @players = User.all
    end
  end

  def ranks
    @ranks = Rank.all
    @dota2 = Rank.where(game_id: 1)
    @cs = Rank.where(game_id: 2)
  end
end

app/views/players/index.html.erb
    <div class="d-flex align-items-center py-3">
      <div class="category">
      <div class="p-2 bg-gradient-dark mr-5"><strong>FILTER BY</strong></div>
      <div class="p-2 bg-gradient-dark mr-5">POSITION <i class="fas fa-caret-down"></i></div>
      <div class="p-2 bg-gradient-dark mr-5">RANK <i class="fas fa-caret-down"></i></div>
      <div class="p-2 bg-gradient-dark mr-5"><strong>SEARCH</strong></div>


      <%= form_tag players_path, method: :get, class: "form-inline" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "ENTER NICKNAME",
          autocomplete: "off"
        %>
      <% end %>
      </div>
    </div>
  <div class="cards-main-player">

    <div class="cards-player" >
      <% @players.each do|player| %>
        <div class="card-wrapper-player">
          <div class="card-wrapper-player-flex">
            <%= link_to player_path(player) do %>
              <div class="avatar-square-player">
                <% if player.photo.attached? %>
                  <%= cl_image_tag player.photo.key, width: 150, height: 150, crop: :thumb, gravity: :face %>
                <% else %>
                  <%= image_tag "avatar_logo.jpg", height: 150, width: 150 %>
                <% end %>
              </div>
            <% end %>
            <div class="card-position">
              <h3><%= player.nickname %></h3>
              <br>
              <p><%= player.position_name.name %></p>
              <div class="card-buttons">
                <%= link_to create_invitation_path(player: player.id, game_id: player.game, position: player.position_name) do %>
                  <div class="player-button-orange">INVITE</div>
                <% end %>
                <%= link_to player_path(player) do %>
                  <div class="player-button-black">BROWSE</div>
                <% end %>
              </div>
            </div>
            <div class="card-position-image">
              <% if player.rank.game.id == 1 %>
                <%= image_tag player.rank.image, height: 50, width: 50, crop: :fill %>
              <% else %>
                <%= image_tag player.rank.image, height: 25, width: 50, crop: :fill %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/players/ranks.html.erb
<div class="container">
  <div class="rank-card">
    <% @ranks.each do |rank| %>
    <div class=
     <% if current_user.show_game == '1' %>
      'rank-card-category-dota2'
      <% elsif current_user.show_game == '2' %>
      'rank-card-category-csgo'
      <% else %>
      'rank-card-category-overwatch'
      <% end %>
     style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url()">
      <% if rank.game.id == 1 %>
        <div> <%= image_tag rank.image, height: 100, width: 100, crop: :fill %> </div>
      <% else %>
        <div> <%= image_tag rank.image, height: 50, width: 100, crop: :fill %> </div>
      <% end %>
      <div class="d-flex flex-column p-2">
        <div class="div"><%= rank.name %></div>
        <div class="div">Rank: <%= rank.rank_position %></div>
        <div class="div">Table Id: <%= rank.id %></div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/players/show.html.erb
<div class="player-wrapper-avatar">
  <div class="player-avatar-big">
  <% if @player.photo.attached? %>
    <%= cl_image_tag @player.photo.key, height: 195, width: 195, crop: :thumb, gravity: :face %>
    <% else %>
    <%= image_tag "avatar_logo.jpg" , height: 195, width: 195, crop: :fill %>
  <% end %>
  </div>
  <div class="player-stats">
    <h1>Nickname: <%= @player.nickname %></h1>
    <h3>Position: <%= @player.position_name.name %></h3>
    <h3>Rank: <%= @player.rank.name %></h3>
    <h3>Region: Germany</h3>
  </div>
  <div class="player-rank">
    <%= image_tag @player.rank.image, size: "125x125", class: "profile-rank-image" %>
  </div>
</div>

<div class="d-flex justify-content-center">
  <div class="player-button-orange-large btn">INVITE</div>
  <div class="player-button-orange-large btn">MESSAGE</div>
  <div class="player-button-orange-large btn">STATS</div>
</div>

<div class = "invitation-wrapper" >
  <% unless @pending_applications.size.zero? %>
    <h2>Pending Invitations</h2>
  <% end %>
  <% @pending_applications.each do |pending_application| %>
    <% if pending_application.owner_approval %>
      <div class="invitation-card d-flex align-items-center">
        <div class="invitation-team-image m-4">
          <% if pending_application.position.team.photo.attached? %>
            <%= cl_image_tag pending_application.position.team.photo.key, height: 90, width: 90 %>
          <% else %>
            <%= image_tag "void.png", height: 90, width: 90, crop: :fill %>
          <% end %>
        </div>

        <%= link_to pending_application.position.team.name, team_positions_path(pending_application.position.team.id) %>
        <div class="player-button-wrapper d-flex">
          <% if pending_application.position.user.nil? %>
            <%= link_to player_approve_path(id:pending_application.id), method: :post do %>
              <div class="player-button-green">APPROVE</div>
            <% end %>
              <div class="player-button-red">DECLINE</div>
          <% else %>
            <td>TOO LATE - POSTION TAKEN</td>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
  <% unless @pending_applications.size.zero? %>
    <h2>My Applications</h2>
  <% end %>
  <% @pending_applications.each do |pending_application| %>
     <% if pending_application.user_approval %>
      <div class="invitation-card d-flex align-items-center">
        <div class="invitation-team-image m-4">
          <% if pending_application.position.team.photo.attached? %>
            <%= cl_image_tag pending_application.position.team.photo.key, height: 90, width: 90 %>
          <% else %>
            <%= image_tag "void.png", height: 90, width: 90, crop: :fill %>
          <% end %>
        </div>
        <%= link_to pending_application.position.team.name, team_positions_path(pending_application.position.team.id) %>
        <div class="player-button-wrapper d-flex">
          <%= link_to team_positions_path(pending_application.position.team.id) do %>
            <div class="player-button-green">VIEW</div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>